### PR TITLE
linked_list.py

### PR DESCRIPTION
**Pull request by shiraz-30**
Implementation of general linked lists in Python.

### CODE REVIEW

**Comment by SuryaSekhar14** [comment]
Can you make this interactive? Take user inputs on which function they want to perform on the Linked List. 
Like insert at Beginning or End, or middle.

**Comment by shiraz-30** [comment]
ok I'll try to add an input method.
after that shall I close the previous PR and commit a new PR? 
or edit the code of the file there itself?

**Comment by SuryaSekhar14** [comment]
Edit this file itself

**Comment by shiraz-30** [comment]
edited the file

**Comment by shiraz-30** [comment]
The contributions I've made to this repository has been marked "Excluded Project" in my Hacktoberfest profile. 
Please check once, how my merged PRs will be counted to HacktoberFest. 
I guess the hacktoberfest-accepted tag has not been tagged onto my contribution.

**Pull request merged**
