### PR TITLE
added a collection of three functions, two that work together to find…

### PR DESCRIPTION
**Pull request by samspark345**
… voting percentage and one for minimum  rectangle in circle

### CODE REVIEW

**Review by SuryaSekhar14 — CHANGES_REQUESTED** [review]
On running the Program, no output is there. Add a main function, and call the 3 functions from within the main function.

Screenshot 2020-10-30 at 2 47 27 AM
.

**Comment by SuryaSekhar14** [comment]
Also, change the file name.

**Comment by SuryaSekhar14** [comment]
[if __name__ == "__main__":]

This is the main function. Print statements won't achieve this. Add function calls under this main function. And upload one file, not 4.

**Comment by SuryaSekhar14** [comment]
if name == "main":

This is the main function. Print statements won't achieve this. Add function calls under this main function. And upload one file, not 4.

**Comment by samspark345** [comment]
ok ill make changes to the voting count one on github and commit it here

**Comment by SuryaSekhar14** [comment]
image

Please run and check before submitting it.

**Comment by SuryaSekhar14** [comment]
It's running now. Good.

**Comment by samspark345** [comment]
i actually ran it, and it works? maybe because i didnt accoount for when there is no input but thats what i did, thank you for noticing that

**Comment by SuryaSekhar14** [comment]
Welcome. It'd be great if you can contribute more to my repos, or even this one. I will be making a bunch of them later, you can follow my profile for updates.

**Comment by samspark345** [comment]
yeah i would be happy to

**Pull request merged**
