### PR TITLE
Re- arrange repository 

### LINKED ISSUE #23: Arrange the Files
Arrange the files into applicable folders. Create new folders.

### PR DESCRIPTION
**Pull request by divshacker**
fixes #23

### CODE REVIEW

**Comment by divshacker** [comment]
Done let me know if there is any program is in wrong folder
Thanks

**Comment by SuryaSekhar14** [comment]
I think its fine

**Comment by divshacker** [comment]
You haven't put the label 😅

**Comment by SuryaSekhar14** [comment]
The repo is marked, so doesn't matter honestly. Done anyway.

**Pull request merged**
