### PR TITLE
Create TextRecognition_using_OpenCV.py

### LINKED ISSUE #27: Add a few Computer Vision related Projects

### PR DESCRIPTION
**Pull request by ankur12-1610**
Fixes: #27

### CODE REVIEW

**Comment by ankur12-1610** [comment]
@SuryaSekhar14 please review the PR!

**Comment by SuryaSekhar14** [comment]
Can you add another project, where the camera input is taken live, and OCR Data is outputted live?

**Comment by ankur12-1610** [comment]
> Can you add another project, where the camera input is taken live, and OCR Data is outputted live?

Yeah Sure.

**Comment by ankur12-1610** [comment]
@SuryaSekhar14 sorry for the disturbance but I have a doubt.
Screenshot-20211004135412-1430x131

Why is it displaying that the project is excluded?

**Pull request merged**
