### PR TITLE
Added few programs in LinkedList

### PR DESCRIPTION
**Pull request by divshacker**

### CODE REVIEW

**Comment by SuryaSekhar14** [comment]
Can you add all the files in a single folder?

**Comment by divshacker** [comment]
Sure

**Comment by divshacker** [comment]
Done @SuryaSekhar14

**Comment by divshacker** [comment]
Please attach the tag too 
Thank you

**Comment by SuryaSekhar14** [comment]
One file is missing the .cpp extention, please add it

**Pull request merged**
